/**
 * ROOTS GALLERY — Product Data
 * Winter 2026 Catalogue
 *
 * Source of truth: stock catalogue PDF (pages 1–5 only).
 * costZAR is internal business data — never display to customers.
 * priceNIS is the customer-facing selling price in Israeli New Shekel (₪).
 * purchasable is false when no confirmed NIS price exists.
 */

const PRODUCTS = [

  // ─── TIKAR BANGLES ────────────────────────────────────────────────────
  {
    id: "tb01",
    slug: "tikar-bangle-tb01",
    styleNumber: "TB01",
    name: "Tikar Bangle",
    category: "tikar-bangles",
    categoryLabel: "Tikar Bangles",
    colour: "Green",
    colourSlug: "green",
    season: "Winter 2026",
    costZAR: 368,
    priceNIS: 350,
    image: "assets/products/winter-2026/tb01.webp",
    thumbnail: "assets/products/winter-2026/tb01.webp",
    images: ["assets/products/winter-2026/tb01.webp"],
    alt: "Green Tikar Bangle, style TB01",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tb02",
    slug: "tikar-bangle-tb02",
    styleNumber: "TB02",
    name: "Tikar Bangle",
    category: "tikar-bangles",
    categoryLabel: "Tikar Bangles",
    colour: "Orange",
    colourSlug: "orange",
    season: "Winter 2026",
    costZAR: 368,
    priceNIS: 350,
    image: "assets/products/winter-2026/tb02.webp",
    thumbnail: "assets/products/winter-2026/tb02.webp",
    images: ["assets/products/winter-2026/tb02.webp"],
    alt: "Orange Tikar Bangle, style TB02",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "tb03",
    slug: "tikar-bangle-tb03",
    styleNumber: "TB03",
    name: "Tikar Bangle",
    category: "tikar-bangles",
    categoryLabel: "Tikar Bangles",
    colour: "Yellow",
    colourSlug: "yellow",
    season: "Winter 2026",
    costZAR: 368,
    priceNIS: 350,
    image: "assets/products/winter-2026/tb03.webp",
    thumbnail: "assets/products/winter-2026/tb03.webp",
    images: ["assets/products/winter-2026/tb03.webp"],
    alt: "Yellow Tikar Bangle, style TB03",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "tb04",
    slug: "tikar-bangle-tb04",
    styleNumber: "TB04",
    name: "Tikar Bangle",
    category: "tikar-bangles",
    categoryLabel: "Tikar Bangles",
    colour: "Yellow",
    colourSlug: "yellow",
    season: "Winter 2026",
    costZAR: 368,
    priceNIS: 350,
    image: "assets/products/winter-2026/tb04.webp",
    thumbnail: "assets/products/winter-2026/tb04.webp",
    images: ["assets/products/winter-2026/tb04.webp"],
    alt: "Yellow Tikar Bangle, style TB04",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "tb05",
    slug: "tikar-bangle-tb05",
    styleNumber: "TB05",
    name: "Tikar Bangle",
    category: "tikar-bangles",
    categoryLabel: "Tikar Bangles",
    colour: "Red",
    colourSlug: "red",
    season: "Winter 2026",
    costZAR: 368,
    priceNIS: 350,
    image: "assets/products/winter-2026/tb05.webp",
    thumbnail: "assets/products/winter-2026/tb05.webp",
    images: ["assets/products/winter-2026/tb05.webp"],
    alt: "Red Tikar Bangle, style TB05",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },

  // ─── NAMJI DOLLS ──────────────────────────────────────────────────────
  {
    id: "dn01",
    slug: "namji-doll-dn01",
    styleNumber: "DN01",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "White",
    colourSlug: "white",
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: 300,
    image: "assets/products/winter-2026/dn01.webp",
    thumbnail: "assets/products/winter-2026/dn01.webp",
    images: ["assets/products/winter-2026/dn01.webp"],
    alt: "White Namji Doll, style DN01",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "dn02",
    slug: "namji-doll-dn02",
    styleNumber: "DN02",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Blue and White",
    colourSlug: "blue-white",
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: 300,
    image: "assets/products/winter-2026/dn02.webp",
    thumbnail: "assets/products/winter-2026/dn02.webp",
    images: ["assets/products/winter-2026/dn02.webp"],
    alt: "Blue and White Namji Doll, style DN02",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "dn03",
    slug: "namji-doll-dn03",
    styleNumber: "DN03",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Black and White",
    colourSlug: "black-white",
    season: "Winter 2026",
    costZAR: 458,
    priceNIS: 425,
    image: "assets/products/winter-2026/dn03.webp",
    thumbnail: "assets/products/winter-2026/dn03.webp",
    images: ["assets/products/winter-2026/dn03.webp"],
    alt: "Black and White Namji Doll, style DN03",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn04",
    slug: "namji-doll-dn04",
    styleNumber: "DN04",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Orange",
    colourSlug: "orange",
    season: "Winter 2026",
    costZAR: 458,
    priceNIS: 425,
    image: "assets/products/winter-2026/dn04.webp",
    thumbnail: "assets/products/winter-2026/dn04.webp",
    images: ["assets/products/winter-2026/dn04.webp"],
    alt: "Orange Namji Doll, style DN04",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn05",
    slug: "namji-doll-dn05",
    styleNumber: "DN05",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Blue and White",
    colourSlug: "blue-white",
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: 300,
    image: "assets/products/winter-2026/dn05.webp",
    thumbnail: "assets/products/winter-2026/dn05.webp",
    images: ["assets/products/winter-2026/dn05.webp"],
    alt: "Blue and White Namji Doll, style DN05",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn06",
    slug: "namji-doll-dn06",
    styleNumber: "DN06",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Black",
    colourSlug: "black",
    season: "Winter 2026",
    costZAR: 168,
    priceNIS: 150,
    image: "assets/products/winter-2026/dn06.webp",
    thumbnail: "assets/products/winter-2026/dn06.webp",
    images: ["assets/products/winter-2026/dn06.webp"],
    alt: "Black Namji Doll, style DN06",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn07",
    slug: "namji-doll-dn07",
    styleNumber: "DN07",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Yellow",
    colourSlug: "yellow",
    season: "Winter 2026",
    costZAR: 108,
    priceNIS: 100,
    image: "assets/products/winter-2026/dn07.webp",
    thumbnail: "assets/products/winter-2026/dn07.webp",
    images: ["assets/products/winter-2026/dn07.webp"],
    alt: "Yellow Namji Doll, style DN07",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn08",
    slug: "namji-doll-dn08",
    styleNumber: "DN08",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Pearl",
    colourSlug: "pearl",
    season: "Winter 2026",
    costZAR: 368,
    priceNIS: 350,
    image: "assets/products/winter-2026/dn08.webp",
    thumbnail: "assets/products/winter-2026/dn08.webp",
    images: ["assets/products/winter-2026/dn08.webp"],
    alt: "Pearl Namji Doll, style DN08",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn09",
    slug: "namji-doll-dn09",
    styleNumber: "DN09",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Pastel Green",
    colourSlug: "pastel-green",
    season: "Winter 2026",
    costZAR: 428,
    priceNIS: 400,
    image: "assets/products/winter-2026/dn09.webp",
    thumbnail: "assets/products/winter-2026/dn09.webp",
    images: ["assets/products/winter-2026/dn09.webp"],
    alt: "Pastel Green Namji Doll, style DN09",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "dn10",
    slug: "namji-doll-dn10",
    styleNumber: "DN10",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Black and White",
    colourSlug: "black-white",
    season: "Winter 2026",
    costZAR: 458,
    priceNIS: 450,
    image: "assets/products/winter-2026/dn10.webp",
    thumbnail: "assets/products/winter-2026/dn10.webp",
    images: ["assets/products/winter-2026/dn10.webp"],
    alt: "Black and White Namji Doll, style DN10",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn11",
    slug: "namji-doll-dn11",
    styleNumber: "DN11",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Yellow",
    colourSlug: "yellow",
    season: "Winter 2026",
    costZAR: 108,
    priceNIS: 100,
    image: "assets/products/winter-2026/dn11.webp",
    thumbnail: "assets/products/winter-2026/dn11.webp",
    images: ["assets/products/winter-2026/dn11.webp"],
    alt: "Yellow Namji Doll, style DN11",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn12",
    slug: "namji-doll-dn12",
    styleNumber: "DN12",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Gold",
    colourSlug: "gold",
    season: "Winter 2026",
    costZAR: 178,
    priceNIS: 160,
    image: "assets/products/winter-2026/dn12.webp",
    thumbnail: "assets/products/winter-2026/dn12.webp",
    images: ["assets/products/winter-2026/dn12.webp"],
    alt: "Gold Namji Doll, style DN12",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn13",
    slug: "namji-doll-dn13",
    styleNumber: "DN13",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Orange",
    colourSlug: "orange",
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: 300,
    image: "assets/products/winter-2026/dn13.webp",
    thumbnail: "assets/products/winter-2026/dn13.webp",
    images: ["assets/products/winter-2026/dn13.webp"],
    alt: "Orange Namji Doll, style DN13",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn14",
    slug: "namji-doll-dn14",
    styleNumber: "DN14",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Pastel Red",
    colourSlug: "pastel-red",
    season: "Winter 2026",
    costZAR: 398,
    priceNIS: 350,
    image: "assets/products/winter-2026/dn14.webp",
    thumbnail: "assets/products/winter-2026/dn14.webp",
    images: ["assets/products/winter-2026/dn14.webp"],
    alt: "Pastel Red Namji Doll, style DN14",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn15",
    slug: "namji-doll-dn15",
    styleNumber: "DN15",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Orange",
    colourSlug: "orange",
    season: "Winter 2026",
    costZAR: 458,
    priceNIS: 450,
    image: "assets/products/winter-2026/dn15.webp",
    thumbnail: "assets/products/winter-2026/dn15.webp",
    images: ["assets/products/winter-2026/dn15.webp"],
    alt: "Orange Namji Doll, style DN15",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn16",
    slug: "namji-doll-dn16",
    styleNumber: "DN16",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "White",
    colourSlug: "white",
    season: "Winter 2026",
    costZAR: 378,
    priceNIS: 350,
    image: "assets/products/winter-2026/dn16.webp",
    thumbnail: "assets/products/winter-2026/dn16.webp",
    images: ["assets/products/winter-2026/dn16.webp"],
    alt: "White Namji Doll, style DN16",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn17",
    slug: "namji-doll-dn17",
    styleNumber: "DN17",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Green",
    colourSlug: "green",
    season: "Winter 2026",
    costZAR: 428,
    priceNIS: 400,
    image: "assets/products/winter-2026/dn17.webp",
    thumbnail: "assets/products/winter-2026/dn17.webp",
    images: ["assets/products/winter-2026/dn17.webp"],
    alt: "Green Namji Doll, style DN17",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn18",
    slug: "namji-doll-dn18",
    styleNumber: "DN18",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Black",
    colourSlug: "black",
    season: "Winter 2026",
    costZAR: 458,
    priceNIS: 450,
    image: "assets/products/winter-2026/dn18.webp",
    thumbnail: "assets/products/winter-2026/dn18.webp",
    images: ["assets/products/winter-2026/dn18.webp"],
    alt: "Black Namji Doll, style DN18",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn19",
    slug: "namji-doll-dn19",
    styleNumber: "DN19",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Rainbow",
    colourSlug: "rainbow",
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: 300,
    image: "assets/products/winter-2026/dn19.webp",
    thumbnail: "assets/products/winter-2026/dn19.webp",
    images: ["assets/products/winter-2026/dn19.webp"],
    alt: "Rainbow Namji Doll, style DN19",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "dn20",
    slug: "namji-doll-dn20",
    styleNumber: "DN20",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Rainbow",
    colourSlug: "rainbow",
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: 300,
    image: "assets/products/winter-2026/dn20.webp",
    thumbnail: "assets/products/winter-2026/dn20.webp",
    images: ["assets/products/winter-2026/dn20.webp"],
    alt: "Rainbow Namji Doll, style DN20",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn21",
    slug: "namji-doll-dn21",
    styleNumber: "DN21",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Yellow",
    colourSlug: "yellow",
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: 300,
    image: "assets/products/winter-2026/dn21.webp",
    thumbnail: "assets/products/winter-2026/dn21.webp",
    images: ["assets/products/winter-2026/dn21.webp"],
    alt: "Yellow Namji Doll, style DN21",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "dn22",
    slug: "namji-doll-dn22",
    styleNumber: "DN22",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Black and White",
    colourSlug: "black-white",
    season: "Winter 2026",
    costZAR: 580,
    priceNIS: 449,
    image: "assets/products/winter-2026/dn22.webp",
    thumbnail: "assets/products/winter-2026/dn22.webp",
    images: ["assets/products/winter-2026/dn22.webp"],
    alt: "Black and White Namji Doll, style DN22",
    purchasable: true,
    requiresPriceConfirmation: false,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "dn23",
    slug: "namji-doll-dn23",
    styleNumber: "DN23",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Black and White",
    colourSlug: "black-white",
    season: "Winter 2026",
    costZAR: 580,
    priceNIS: null,
    image: "assets/products/winter-2026/dn23.webp",
    thumbnail: "assets/products/winter-2026/dn23.webp",
    images: ["assets/products/winter-2026/dn23.webp"],
    alt: "Black and White Namji Doll, style DN23",
    purchasable: false,
    requiresPriceConfirmation: true,
  },
  {
    id: "dn24",
    slug: "namji-doll-dn24",
    styleNumber: "DN24",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "Black",
    colourSlug: "black",
    season: "Winter 2026",
    costZAR: 580,
    priceNIS: null,
    image: "assets/products/winter-2026/dn24.webp",
    thumbnail: "assets/products/winter-2026/dn24.webp",
    images: ["assets/products/winter-2026/dn24.webp"],
    alt: "Black Namji Doll, style DN24",
    purchasable: false,
    requiresPriceConfirmation: false,
  },
  {
    id: "dn25",
    slug: "namji-doll-dn25",
    styleNumber: "DN25",
    name: "Namji Doll",
    category: "namji-dolls",
    categoryLabel: "Namji Dolls",
    colour: "White",
    colourSlug: "white",
    season: "Winter 2026",
    costZAR: 880,
    priceNIS: null,
    image: "assets/products/winter-2026/dn25.webp",
    thumbnail: "assets/products/winter-2026/dn25.webp",
    images: ["assets/products/winter-2026/dn25.webp"],
    alt: "White Namji Doll, style DN25",
    purchasable: false,
    requiresPriceConfirmation: false,
  },

  // ─── WOVEN BASKETS ────────────────────────────────────────────────────
  {
    id: "bt01",
    slug: "woven-basket-bt01",
    styleNumber: "BT01",
    name: "Woven Basket",
    category: "woven-baskets",
    categoryLabel: "Woven Baskets",
    colour: "Beige and Brown",
    colourSlug: "beige-brown",
    season: "Winter 2026",
    costZAR: 128,
    priceNIS: null,
    image: "assets/products/winter-2026/bt01.webp",
    thumbnail: "assets/products/winter-2026/bt01.webp",
    images: ["assets/products/winter-2026/bt01.webp"],
    alt: "Beige and Brown Woven Basket, style BT01",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "bt02",
    slug: "woven-basket-bt02",
    styleNumber: "BT02",
    name: "Woven Basket",
    category: "woven-baskets",
    categoryLabel: "Woven Baskets",
    colour: "Beige and Brown",
    colourSlug: "beige-brown",
    season: "Winter 2026",
    costZAR: 138,
    priceNIS: null,
    image: "assets/products/winter-2026/bt02.webp",
    thumbnail: "assets/products/winter-2026/bt02.webp",
    images: ["assets/products/winter-2026/bt02.webp"],
    alt: "Beige and Brown Woven Basket, style BT02",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "bt03",
    slug: "woven-basket-bt03",
    styleNumber: "BT03",
    name: "Woven Basket",
    category: "woven-baskets",
    categoryLabel: "Woven Baskets",
    colour: "Beige and Brown",
    colourSlug: "beige-brown",
    season: "Winter 2026",
    costZAR: 128,
    priceNIS: null,
    image: "assets/products/winter-2026/bt03.webp",
    thumbnail: "assets/products/winter-2026/bt03.webp",
    images: ["assets/products/winter-2026/bt03.webp"],
    alt: "Beige and Brown Woven Basket, style BT03",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "bt04",
    slug: "woven-basket-bt04",
    styleNumber: "BT04",
    name: "Woven Basket",
    category: "woven-baskets",
    categoryLabel: "Woven Baskets",
    colour: "Beige and Brown",
    colourSlug: "beige-brown",
    season: "Winter 2026",
    costZAR: 138,
    priceNIS: null,
    image: "assets/products/winter-2026/bt04.webp",
    thumbnail: "assets/products/winter-2026/bt04.webp",
    images: ["assets/products/winter-2026/bt04.webp"],
    alt: "Beige and Brown Woven Basket, style BT04",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },

  // ─── WOODEN BOWLS ─────────────────────────────────────────────────────
  {
    id: "w01",
    slug: "wooden-bowl-w01",
    styleNumber: "W01",
    name: "Wooden Bowl",
    category: "wooden-bowls",
    categoryLabel: "Wooden Bowls",
    colour: null,
    colourSlug: null,
    season: "Winter 2026",
    costZAR: 268,
    priceNIS: null,
    image: "assets/products/winter-2026/w01.webp",
    thumbnail: "assets/products/winter-2026/w01.webp",
    images: ["assets/products/winter-2026/w01.webp"],
    alt: "Wooden Bowl, style W01",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "w02",
    slug: "wooden-bowl-w02",
    styleNumber: "W02",
    name: "Wooden Bowl",
    category: "wooden-bowls",
    categoryLabel: "Wooden Bowls",
    colour: null,
    colourSlug: null,
    season: "Winter 2026",
    costZAR: 268,
    priceNIS: null,
    image: "assets/products/winter-2026/w02.webp",
    thumbnail: "assets/products/winter-2026/w02.webp",
    images: ["assets/products/winter-2026/w02.webp"],
    alt: "Wooden Bowl, style W02",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "w03",
    slug: "wooden-bowl-w03",
    styleNumber: "W03",
    name: "Wooden Bowl",
    category: "wooden-bowls",
    categoryLabel: "Wooden Bowls",
    colour: null,
    colourSlug: null,
    season: "Winter 2026",
    costZAR: 328,
    priceNIS: null,
    image: "assets/products/winter-2026/w03.webp",
    thumbnail: "assets/products/winter-2026/w03.webp",
    images: ["assets/products/winter-2026/w03.webp"],
    alt: "Wooden Bowl, style W03",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "w04",
    slug: "wooden-bowl-w04",
    styleNumber: "W04",
    name: "Wooden Bowl",
    category: "wooden-bowls",
    categoryLabel: "Wooden Bowls",
    colour: null,
    colourSlug: null,
    season: "Winter 2026",
    costZAR: 268,
    priceNIS: null,
    image: "assets/products/winter-2026/w04.webp",
    thumbnail: "assets/products/winter-2026/w04.webp",
    images: ["assets/products/winter-2026/w04.webp"],
    alt: "Wooden Bowl, style W04",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },

  // ─── SMALL BOWLS ──────────────────────────────────────────────────────
  {
    id: "z01",
    slug: "small-bowl-z01",
    styleNumber: "Z01",
    name: "Small Bowl",
    category: "small-bowls",
    categoryLabel: "Small Bowls",
    colour: null,
    colourSlug: null,
    season: "Winter 2026",
    costZAR: 120,
    priceNIS: null,
    image: "assets/products/winter-2026/z01.webp",
    thumbnail: "assets/products/winter-2026/z01.webp",
    images: ["assets/products/winter-2026/z01.webp"],
    alt: "Small Bowl, style Z01",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "z02",
    slug: "small-bowl-z02",
    styleNumber: "Z02",
    name: "Small Bowl",
    category: "small-bowls",
    categoryLabel: "Small Bowls",
    colour: null,
    colourSlug: null,
    season: "Winter 2026",
    costZAR: 120,
    priceNIS: null,
    image: "assets/products/winter-2026/z02.webp",
    thumbnail: "assets/products/winter-2026/z02.webp",
    images: ["assets/products/winter-2026/z02.webp"],
    alt: "Small Bowl, style Z02",
    purchasable: false,
    requiresPriceConfirmation: false,
    isFeatured: false,
    isNew: true,
  },
];

// ─── Lookup helpers ──────────────────────────────────────────────────

function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null;
}

function getProductsByCategory(category) {
  return PRODUCTS.filter(p => p.category === category);
}

function getFeaturedProducts() {
  return PRODUCTS.filter(p => p.isFeatured);
}

function getNewArrivals() {
  return PRODUCTS.filter(p => p.isNew);
}

// ─── Price formatter (NIS / Israeli New Shekel) ──────────────────────

function formatPriceNIS(amount) {
  return `\u20AA${Number(amount).toLocaleString('en-US', { minimumFractionDigits: 0 })}`;
}

// Alias kept for any legacy references
const formatPriceUSD = formatPriceNIS;

// ─── Filter options ──────────────────────────────────────────────────

const FILTER_OPTIONS = {
  categories: [
    { value: "namji-dolls",   label: "Namji Dolls" },
    { value: "tikar-bangles", label: "Tikar Bangles" },
    { value: "woven-baskets", label: "Woven Baskets" },
    { value: "wooden-bowls",  label: "Wooden Bowls" },
    { value: "small-bowls",   label: "Small Bowls" },
  ],
  colors: [
    { value: "black",        label: "Black" },
    { value: "black-white",  label: "Black & White" },
    { value: "beige-brown",  label: "Beige & Brown" },
    { value: "blue-white",   label: "Blue & White" },
    { value: "gold",         label: "Gold" },
    { value: "green",        label: "Green" },
    { value: "orange",       label: "Orange" },
    { value: "pastel-green", label: "Pastel Green" },
    { value: "pastel-red",   label: "Pastel Red" },
    { value: "pearl",        label: "Pearl" },
    { value: "rainbow",      label: "Rainbow" },
    { value: "red",          label: "Red" },
    { value: "white",        label: "White" },
    { value: "yellow",       label: "Yellow" },
  ],
  availability: [
    { value: "purchasable",  label: "Price Available" },
    { value: "enquire",      label: "Enquire for Price" },
  ],
};

// ─── Sort products ───────────────────────────────────────────────────

function sortProducts(products, sortBy) {
  const list = [...products];
  switch (sortBy) {
    case "newest":
      return list.sort((a, b) => (b.isNew ? 1 : 0) - (a.isNew ? 1 : 0));
    case "price-asc":
      return list.sort((a, b) => {
        if (a.priceNIS === null && b.priceNIS === null) return 0;
        if (a.priceNIS === null) return 1;
        if (b.priceNIS === null) return -1;
        return a.priceNIS - b.priceNIS;
      });
    case "price-desc":
      return list.sort((a, b) => {
        if (a.priceNIS === null && b.priceNIS === null) return 0;
        if (a.priceNIS === null) return 1;
        if (b.priceNIS === null) return -1;
        return b.priceNIS - a.priceNIS;
      });
    case "featured":
    default:
      return list.sort((a, b) => (b.isFeatured ? 1 : 0) - (a.isFeatured ? 1 : 0));
  }
}

// ─── Filter products ─────────────────────────────────────────────────

function filterProducts(products, filters = {}) {
  return products.filter(p => {
    if (filters.categories && filters.categories.length > 0) {
      if (!filters.categories.includes(p.category)) return false;
    }
    if (filters.colors && filters.colors.length > 0) {
      if (!p.colourSlug || !filters.colors.includes(p.colourSlug)) return false;
    }
    if (filters.availability && filters.availability.length > 0) {
      const status = p.purchasable ? 'purchasable' : 'enquire';
      if (!filters.availability.includes(status)) return false;
    }
    if (filters.minPrice !== undefined && filters.minPrice !== null) {
      if (p.priceNIS === null || p.priceNIS < filters.minPrice) return false;
    }
    if (filters.maxPrice !== undefined && filters.maxPrice !== null) {
      if (p.priceNIS === null || p.priceNIS > filters.maxPrice) return false;
    }
    return true;
  });
}

// Export for module contexts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    PRODUCTS, FILTER_OPTIONS,
    getProductBySlug, getProductsByCategory, getFeaturedProducts, getNewArrivals,
    formatPriceNIS, formatPriceUSD, sortProducts, filterProducts,
  };
}
